services:
  app:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: base
    develop:
      watch:
        - action: sync
          path: back
          target: app/src
          ignore:
            - node_modules/
            - data/
            - RES/
        - action: rebuild
          path: package.json
    command: npm start
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_STORAGE: /app/data/database.sqlite # –ü—É—Ç—å –≤–Ω—É—Ç—Ä–∏ –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞
    ports:
      - "3000:3000"
    volumes:
      # üîΩ –í–ê–ñ–ù–û: –ü–µ—Ä—Å–∏—Å—Ç–µ–Ω—Ç–Ω–æ—Å—Ç—å —Ñ–∞–π–ª–∞ –ë–î
      - ./back/data:/app/data
